version: "3.9"

services:
  backend:
    build: ./back_todo
    ports:
      - "3005:3005"
    env_file:
      - ./back_todo/.env
    restart: always

  frontend:
    build: ./todo-front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
